name: Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Checkout codice sorgente
      - uses: actions/checkout@v3

      # Configurazione ambiente Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # Compilazione
      - run: mvn clean compile
        
      # Esecuzione test
      - run: mvn clean test jacoco:report

      # Analisi statica
      - run: mvn checkstyle:check
      
      # Invio risultati a Coveralls
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
