name: Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Checkout codice sorgente
      - uses: actions/checkout@v3

      # Configurazione ambiente Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # Compilazione
      - run: mvn clean compile

      # Esecuzione test
      - run: mvn clean test jacoco:report coveralls:report

      #Coveralls token
      - env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: mvn coveralls:report -DrepoToken=$COVERALLS_TOKEN

      # Analisi statica
      - run: mvn package
